spring:
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
    dynamic:
      p6spy: true
      # 配置全局druid参数，请按需配置
      druid:
        initial-size: 5
        max-active: 8
        min-idle: 3
        max-wait: 1000
        validation-query: 'select 1'
      datasource:
        master:
          username: root
          password: "King1234."
          url: jdbc:mysql://127.0.0.1:3306/ddddd?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave_1:
          username: root
          password: "King1234."
          url: jdbc:mysql://127.0.0.1:3306/demo1?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
          driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.baomidou: debug